//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteVerificar.ServicioActualizacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioActualizacion.ActualizacionSoap")]
    public interface ActualizacionSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClienteVerificar.ServicioActualizacion.HelloWorldResponse HelloWorld(ClienteVerificar.ServicioActualizacion.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name hash from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarVersion", ReplyAction="*")]
        ClienteVerificar.ServicioActualizacion.VerificarVersionResponse VerificarVersion(ClienteVerificar.ServicioActualizacion.VerificarVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClienteVerificar.ServicioActualizacion.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClienteVerificar.ServicioActualizacion.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteVerificar.ServicioActualizacion.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClienteVerificar.ServicioActualizacion.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarVersion", Namespace="http://tempuri.org/", Order=0)]
        public ClienteVerificar.ServicioActualizacion.VerificarVersionRequestBody Body;
        
        public VerificarVersionRequest() {
        }
        
        public VerificarVersionRequest(ClienteVerificar.ServicioActualizacion.VerificarVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hash;
        
        public VerificarVersionRequestBody() {
        }
        
        public VerificarVersionRequestBody(string hash) {
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteVerificar.ServicioActualizacion.VerificarVersionResponseBody Body;
        
        public VerificarVersionResponse() {
        }
        
        public VerificarVersionResponse(ClienteVerificar.ServicioActualizacion.VerificarVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarVersionResult;
        
        public VerificarVersionResponseBody() {
        }
        
        public VerificarVersionResponseBody(bool VerificarVersionResult) {
            this.VerificarVersionResult = VerificarVersionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActualizacionSoapChannel : ClienteVerificar.ServicioActualizacion.ActualizacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActualizacionSoapClient : System.ServiceModel.ClientBase<ClienteVerificar.ServicioActualizacion.ActualizacionSoap>, ClienteVerificar.ServicioActualizacion.ActualizacionSoap {
        
        public ActualizacionSoapClient() {
        }
        
        public ActualizacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActualizacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActualizacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActualizacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteVerificar.ServicioActualizacion.HelloWorldResponse ClienteVerificar.ServicioActualizacion.ActualizacionSoap.HelloWorld(ClienteVerificar.ServicioActualizacion.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClienteVerificar.ServicioActualizacion.HelloWorldRequest inValue = new ClienteVerificar.ServicioActualizacion.HelloWorldRequest();
            inValue.Body = new ClienteVerificar.ServicioActualizacion.HelloWorldRequestBody();
            ClienteVerificar.ServicioActualizacion.HelloWorldResponse retVal = ((ClienteVerificar.ServicioActualizacion.ActualizacionSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteVerificar.ServicioActualizacion.VerificarVersionResponse ClienteVerificar.ServicioActualizacion.ActualizacionSoap.VerificarVersion(ClienteVerificar.ServicioActualizacion.VerificarVersionRequest request) {
            return base.Channel.VerificarVersion(request);
        }
        
        public bool VerificarVersion(string hash) {
            ClienteVerificar.ServicioActualizacion.VerificarVersionRequest inValue = new ClienteVerificar.ServicioActualizacion.VerificarVersionRequest();
            inValue.Body = new ClienteVerificar.ServicioActualizacion.VerificarVersionRequestBody();
            inValue.Body.hash = hash;
            ClienteVerificar.ServicioActualizacion.VerificarVersionResponse retVal = ((ClienteVerificar.ServicioActualizacion.ActualizacionSoap)(this)).VerificarVersion(inValue);
            return retVal.Body.VerificarVersionResult;
        }
    }
}
