//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TSCIModel", "FK_TblVentas_TblAutos", "TblAutos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GeneracionCodigoReflexion.TblAutos), "TblVentas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GeneracionCodigoReflexion.TblVentas), true)]
[assembly: EdmRelationshipAttribute("TSCIModel", "FK_TblVentas_TblClientes", "TblClientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GeneracionCodigoReflexion.TblClientes), "TblVentas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GeneracionCodigoReflexion.TblVentas), true)]

#endregion

namespace GeneracionCodigoReflexion
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TSCIEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TSCIEntities object using the connection string found in the 'TSCIEntities' section of the application configuration file.
        /// </summary>
        public TSCIEntities() : base("name=TSCIEntities", "TSCIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TSCIEntities object.
        /// </summary>
        public TSCIEntities(string connectionString) : base(connectionString, "TSCIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TSCIEntities object.
        /// </summary>
        public TSCIEntities(EntityConnection connection) : base(connection, "TSCIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblAutos> TblAutos
        {
            get
            {
                if ((_TblAutos == null))
                {
                    _TblAutos = base.CreateObjectSet<TblAutos>("TblAutos");
                }
                return _TblAutos;
            }
        }
        private ObjectSet<TblAutos> _TblAutos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblClientes> TblClientes
        {
            get
            {
                if ((_TblClientes == null))
                {
                    _TblClientes = base.CreateObjectSet<TblClientes>("TblClientes");
                }
                return _TblClientes;
            }
        }
        private ObjectSet<TblClientes> _TblClientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblVentas> TblVentas
        {
            get
            {
                if ((_TblVentas == null))
                {
                    _TblVentas = base.CreateObjectSet<TblVentas>("TblVentas");
                }
                return _TblVentas;
            }
        }
        private ObjectSet<TblVentas> _TblVentas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblAutos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblAutos(TblAutos tblAutos)
        {
            base.AddObject("TblAutos", tblAutos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblClientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblClientes(TblClientes tblClientes)
        {
            base.AddObject("TblClientes", tblClientes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblVentas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblVentas(TblVentas tblVentas)
        {
            base.AddObject("TblVentas", tblVentas);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSCIModel", Name="TblAutos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblAutos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblAutos object.
        /// </summary>
        /// <param name="idAuto">Initial value of the IdAuto property.</param>
        /// <param name="modelo">Initial value of the Modelo property.</param>
        /// <param name="marca">Initial value of the Marca property.</param>
        /// <param name="anio">Initial value of the Anio property.</param>
        public static TblAutos CreateTblAutos(global::System.Int32 idAuto, global::System.String modelo, global::System.String marca, global::System.Int32 anio)
        {
            TblAutos tblAutos = new TblAutos();
            tblAutos.IdAuto = idAuto;
            tblAutos.Modelo = modelo;
            tblAutos.Marca = marca;
            tblAutos.Anio = anio;
            return tblAutos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdAuto
        {
            get
            {
                return _IdAuto;
            }
            set
            {
                if (_IdAuto != value)
                {
                    OnIdAutoChanging(value);
                    ReportPropertyChanging("IdAuto");
                    _IdAuto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdAuto");
                    OnIdAutoChanged();
                }
            }
        }
        private global::System.Int32 _IdAuto;
        partial void OnIdAutoChanging(global::System.Int32 value);
        partial void OnIdAutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Modelo
        {
            get
            {
                return _Modelo;
            }
            set
            {
                OnModeloChanging(value);
                ReportPropertyChanging("Modelo");
                _Modelo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Modelo");
                OnModeloChanged();
            }
        }
        private global::System.String _Modelo;
        partial void OnModeloChanging(global::System.String value);
        partial void OnModeloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Marca
        {
            get
            {
                return _Marca;
            }
            set
            {
                OnMarcaChanging(value);
                ReportPropertyChanging("Marca");
                _Marca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Marca");
                OnMarcaChanged();
            }
        }
        private global::System.String _Marca;
        partial void OnMarcaChanging(global::System.String value);
        partial void OnMarcaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Anio
        {
            get
            {
                return _Anio;
            }
            set
            {
                OnAnioChanging(value);
                ReportPropertyChanging("Anio");
                _Anio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Anio");
                OnAnioChanged();
            }
        }
        private global::System.Int32 _Anio;
        partial void OnAnioChanging(global::System.Int32 value);
        partial void OnAnioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSCIModel", "FK_TblVentas_TblAutos", "TblVentas")]
        public EntityCollection<TblVentas> TblVentas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblVentas>("TSCIModel.FK_TblVentas_TblAutos", "TblVentas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblVentas>("TSCIModel.FK_TblVentas_TblAutos", "TblVentas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSCIModel", Name="TblClientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblClientes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblClientes object.
        /// </summary>
        /// <param name="idCliente">Initial value of the IdCliente property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="appPaterno">Initial value of the AppPaterno property.</param>
        public static TblClientes CreateTblClientes(global::System.Int32 idCliente, global::System.String nombre, global::System.String appPaterno)
        {
            TblClientes tblClientes = new TblClientes();
            tblClientes.IdCliente = idCliente;
            tblClientes.Nombre = nombre;
            tblClientes.AppPaterno = appPaterno;
            return tblClientes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AppPaterno
        {
            get
            {
                return _AppPaterno;
            }
            set
            {
                OnAppPaternoChanging(value);
                ReportPropertyChanging("AppPaterno");
                _AppPaterno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AppPaterno");
                OnAppPaternoChanged();
            }
        }
        private global::System.String _AppPaterno;
        partial void OnAppPaternoChanging(global::System.String value);
        partial void OnAppPaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AppMaterno
        {
            get
            {
                return _AppMaterno;
            }
            set
            {
                OnAppMaternoChanging(value);
                ReportPropertyChanging("AppMaterno");
                _AppMaterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AppMaterno");
                OnAppMaternoChanged();
            }
        }
        private global::System.String _AppMaterno;
        partial void OnAppMaternoChanging(global::System.String value);
        partial void OnAppMaternoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSCIModel", "FK_TblVentas_TblClientes", "TblVentas")]
        public EntityCollection<TblVentas> TblVentas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblVentas>("TSCIModel.FK_TblVentas_TblClientes", "TblVentas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblVentas>("TSCIModel.FK_TblVentas_TblClientes", "TblVentas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSCIModel", Name="TblVentas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblVentas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblVentas object.
        /// </summary>
        /// <param name="idCliente">Initial value of the IdCliente property.</param>
        /// <param name="idAuto">Initial value of the IdAuto property.</param>
        /// <param name="monto">Initial value of the Monto property.</param>
        public static TblVentas CreateTblVentas(global::System.Int32 idCliente, global::System.Int32 idAuto, global::System.String monto)
        {
            TblVentas tblVentas = new TblVentas();
            tblVentas.IdCliente = idCliente;
            tblVentas.IdAuto = idAuto;
            tblVentas.Monto = monto;
            return tblVentas;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdAuto
        {
            get
            {
                return _IdAuto;
            }
            set
            {
                if (_IdAuto != value)
                {
                    OnIdAutoChanging(value);
                    ReportPropertyChanging("IdAuto");
                    _IdAuto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdAuto");
                    OnIdAutoChanged();
                }
            }
        }
        private global::System.Int32 _IdAuto;
        partial void OnIdAutoChanging(global::System.Int32 value);
        partial void OnIdAutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.String _Monto;
        partial void OnMontoChanging(global::System.String value);
        partial void OnMontoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSCIModel", "FK_TblVentas_TblAutos", "TblAutos")]
        public TblAutos TblAutos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblAutos>("TSCIModel.FK_TblVentas_TblAutos", "TblAutos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblAutos>("TSCIModel.FK_TblVentas_TblAutos", "TblAutos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblAutos> TblAutosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblAutos>("TSCIModel.FK_TblVentas_TblAutos", "TblAutos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblAutos>("TSCIModel.FK_TblVentas_TblAutos", "TblAutos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSCIModel", "FK_TblVentas_TblClientes", "TblClientes")]
        public TblClientes TblClientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblClientes>("TSCIModel.FK_TblVentas_TblClientes", "TblClientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblClientes>("TSCIModel.FK_TblVentas_TblClientes", "TblClientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblClientes> TblClientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblClientes>("TSCIModel.FK_TblVentas_TblClientes", "TblClientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblClientes>("TSCIModel.FK_TblVentas_TblClientes", "TblClientes", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
