//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Metro
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class db_socialsensorEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new db_socialsensorEntities object using the connection string found in the 'db_socialsensorEntities' section of the application configuration file.
        /// </summary>
        public db_socialsensorEntities() : base("name=db_socialsensorEntities", "db_socialsensorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db_socialsensorEntities object.
        /// </summary>
        public db_socialsensorEntities(string connectionString) : base(connectionString, "db_socialsensorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db_socialsensorEntities object.
        /// </summary>
        public db_socialsensorEntities(EntityConnection connection) : base(connection, "db_socialsensorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_historical_interactions_data_game> tbl_historical_interactions_data_game
        {
            get
            {
                if ((_tbl_historical_interactions_data_game == null))
                {
                    _tbl_historical_interactions_data_game = base.CreateObjectSet<tbl_historical_interactions_data_game>("tbl_historical_interactions_data_game");
                }
                return _tbl_historical_interactions_data_game;
            }
        }
        private ObjectSet<tbl_historical_interactions_data_game> _tbl_historical_interactions_data_game;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_historical_objectives_data_game> tbl_historical_objectives_data_game
        {
            get
            {
                if ((_tbl_historical_objectives_data_game == null))
                {
                    _tbl_historical_objectives_data_game = base.CreateObjectSet<tbl_historical_objectives_data_game>("tbl_historical_objectives_data_game");
                }
                return _tbl_historical_objectives_data_game;
            }
        }
        private ObjectSet<tbl_historical_objectives_data_game> _tbl_historical_objectives_data_game;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_interpretation_correlation> tbl_interpretation_correlation
        {
            get
            {
                if ((_tbl_interpretation_correlation == null))
                {
                    _tbl_interpretation_correlation = base.CreateObjectSet<tbl_interpretation_correlation>("tbl_interpretation_correlation");
                }
                return _tbl_interpretation_correlation;
            }
        }
        private ObjectSet<tbl_interpretation_correlation> _tbl_interpretation_correlation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_pearson_significance> tbl_pearson_significance
        {
            get
            {
                if ((_tbl_pearson_significance == null))
                {
                    _tbl_pearson_significance = base.CreateObjectSet<tbl_pearson_significance>("tbl_pearson_significance");
                }
                return _tbl_pearson_significance;
            }
        }
        private ObjectSet<tbl_pearson_significance> _tbl_pearson_significance;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_spearmen_significance> tbl_spearmen_significance
        {
            get
            {
                if ((_tbl_spearmen_significance == null))
                {
                    _tbl_spearmen_significance = base.CreateObjectSet<tbl_spearmen_significance>("tbl_spearmen_significance");
                }
                return _tbl_spearmen_significance;
            }
        }
        private ObjectSet<tbl_spearmen_significance> _tbl_spearmen_significance;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_historical_interactions_data_game EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_historical_interactions_data_game(tbl_historical_interactions_data_game tbl_historical_interactions_data_game)
        {
            base.AddObject("tbl_historical_interactions_data_game", tbl_historical_interactions_data_game);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_historical_objectives_data_game EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_historical_objectives_data_game(tbl_historical_objectives_data_game tbl_historical_objectives_data_game)
        {
            base.AddObject("tbl_historical_objectives_data_game", tbl_historical_objectives_data_game);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_interpretation_correlation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_interpretation_correlation(tbl_interpretation_correlation tbl_interpretation_correlation)
        {
            base.AddObject("tbl_interpretation_correlation", tbl_interpretation_correlation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_pearson_significance EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_pearson_significance(tbl_pearson_significance tbl_pearson_significance)
        {
            base.AddObject("tbl_pearson_significance", tbl_pearson_significance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_spearmen_significance EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_spearmen_significance(tbl_spearmen_significance tbl_spearmen_significance)
        {
            base.AddObject("tbl_spearmen_significance", tbl_spearmen_significance);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_socialsensorModel", Name="tbl_historical_interactions_data_game")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_historical_interactions_data_game : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_historical_interactions_data_game object.
        /// </summary>
        /// <param name="idHistorical">Initial value of the IdHistorical property.</param>
        /// <param name="w">Initial value of the W property.</param>
        public static tbl_historical_interactions_data_game Createtbl_historical_interactions_data_game(global::System.Int32 idHistorical, global::System.Int32 w)
        {
            tbl_historical_interactions_data_game tbl_historical_interactions_data_game = new tbl_historical_interactions_data_game();
            tbl_historical_interactions_data_game.IdHistorical = idHistorical;
            tbl_historical_interactions_data_game.W = w;
            return tbl_historical_interactions_data_game;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdHistorical
        {
            get
            {
                return _IdHistorical;
            }
            set
            {
                if (_IdHistorical != value)
                {
                    OnIdHistoricalChanging(value);
                    ReportPropertyChanging("IdHistorical");
                    _IdHistorical = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdHistorical");
                    OnIdHistoricalChanged();
                }
            }
        }
        private global::System.Int32 _IdHistorical;
        partial void OnIdHistoricalChanging(global::System.Int32 value);
        partial void OnIdHistoricalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdRow
        {
            get
            {
                return _IdRow;
            }
            set
            {
                OnIdRowChanging(value);
                ReportPropertyChanging("IdRow");
                _IdRow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdRow");
                OnIdRowChanged();
            }
        }
        private global::System.String _IdRow;
        partial void OnIdRowChanging(global::System.String value);
        partial void OnIdRowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> G
        {
            get
            {
                return _G;
            }
            set
            {
                OnGChanging(value);
                ReportPropertyChanging("G");
                _G = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("G");
                OnGChanged();
            }
        }
        private Nullable<global::System.Int32> _G;
        partial void OnGChanging(Nullable<global::System.Int32> value);
        partial void OnGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 W
        {
            get
            {
                return _W;
            }
            set
            {
                OnWChanging(value);
                ReportPropertyChanging("W");
                _W = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("W");
                OnWChanged();
            }
        }
        private global::System.Int32 _W;
        partial void OnWChanging(global::System.Int32 value);
        partial void OnWChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> T
        {
            get
            {
                return _T;
            }
            set
            {
                OnTChanging(value);
                ReportPropertyChanging("T");
                _T = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("T");
                OnTChanged();
            }
        }
        private Nullable<global::System.Int32> _T;
        partial void OnTChanging(Nullable<global::System.Int32> value);
        partial void OnTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CN
        {
            get
            {
                return _CN;
            }
            set
            {
                OnCNChanging(value);
                ReportPropertyChanging("CN");
                _CN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CN");
                OnCNChanged();
            }
        }
        private Nullable<global::System.Int32> _CN;
        partial void OnCNChanging(Nullable<global::System.Int32> value);
        partial void OnCNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String U
        {
            get
            {
                return _U;
            }
            set
            {
                OnUChanging(value);
                ReportPropertyChanging("U");
                _U = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("U");
                OnUChanged();
            }
        }
        private global::System.String _U;
        partial void OnUChanging(global::System.String value);
        partial void OnUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DATE
        {
            get
            {
                return _DATE;
            }
            set
            {
                OnDATEChanging(value);
                ReportPropertyChanging("DATE");
                _DATE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DATE");
                OnDATEChanged();
            }
        }
        private global::System.String _DATE;
        partial void OnDATEChanging(global::System.String value);
        partial void OnDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TIME
        {
            get
            {
                return _TIME;
            }
            set
            {
                OnTIMEChanging(value);
                ReportPropertyChanging("TIME");
                _TIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TIME");
                OnTIMEChanged();
            }
        }
        private global::System.String _TIME;
        partial void OnTIMEChanging(global::System.String value);
        partial void OnTIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GAMEMODE
        {
            get
            {
                return _GAMEMODE;
            }
            set
            {
                OnGAMEMODEChanging(value);
                ReportPropertyChanging("GAMEMODE");
                _GAMEMODE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GAMEMODE");
                OnGAMEMODEChanged();
            }
        }
        private Nullable<global::System.Int32> _GAMEMODE;
        partial void OnGAMEMODEChanging(Nullable<global::System.Int32> value);
        partial void OnGAMEMODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HOST
        {
            get
            {
                return _HOST;
            }
            set
            {
                OnHOSTChanging(value);
                ReportPropertyChanging("HOST");
                _HOST = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HOST");
                OnHOSTChanged();
            }
        }
        private global::System.String _HOST;
        partial void OnHOSTChanging(global::System.String value);
        partial void OnHOSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> I_VM
        {
            get
            {
                return _I_VM;
            }
            set
            {
                OnI_VMChanging(value);
                ReportPropertyChanging("I_VM");
                _I_VM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_VM");
                OnI_VMChanged();
            }
        }
        private Nullable<global::System.Int32> _I_VM;
        partial void OnI_VMChanging(Nullable<global::System.Int32> value);
        partial void OnI_VMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> I_VST
        {
            get
            {
                return _I_VST;
            }
            set
            {
                OnI_VSTChanging(value);
                ReportPropertyChanging("I_VST");
                _I_VST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_VST");
                OnI_VSTChanged();
            }
        }
        private Nullable<global::System.Int32> _I_VST;
        partial void OnI_VSTChanging(Nullable<global::System.Int32> value);
        partial void OnI_VSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> I_CW
        {
            get
            {
                return _I_CW;
            }
            set
            {
                OnI_CWChanging(value);
                ReportPropertyChanging("I_CW");
                _I_CW = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_CW");
                OnI_CWChanged();
            }
        }
        private Nullable<global::System.Int32> _I_CW;
        partial void OnI_CWChanging(Nullable<global::System.Int32> value);
        partial void OnI_CWChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> I_SH
        {
            get
            {
                return _I_SH;
            }
            set
            {
                OnI_SHChanging(value);
                ReportPropertyChanging("I_SH");
                _I_SH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_SH");
                OnI_SHChanged();
            }
        }
        private Nullable<global::System.Int32> _I_SH;
        partial void OnI_SHChanging(Nullable<global::System.Int32> value);
        partial void OnI_SHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> I_ESH
        {
            get
            {
                return _I_ESH;
            }
            set
            {
                OnI_ESHChanging(value);
                ReportPropertyChanging("I_ESH");
                _I_ESH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_ESH");
                OnI_ESHChanged();
            }
        }
        private Nullable<global::System.Int32> _I_ESH;
        partial void OnI_ESHChanging(Nullable<global::System.Int32> value);
        partial void OnI_ESHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> I_FSH
        {
            get
            {
                return _I_FSH;
            }
            set
            {
                OnI_FSHChanging(value);
                ReportPropertyChanging("I_FSH");
                _I_FSH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_FSH");
                OnI_FSHChanged();
            }
        }
        private Nullable<global::System.Int32> _I_FSH;
        partial void OnI_FSHChanging(Nullable<global::System.Int32> value);
        partial void OnI_FSHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> N_I_ESHT
        {
            get
            {
                return _N_I_ESHT;
            }
            set
            {
                OnN_I_ESHTChanging(value);
                ReportPropertyChanging("N_I_ESHT");
                _N_I_ESHT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("N_I_ESHT");
                OnN_I_ESHTChanged();
            }
        }
        private Nullable<global::System.Int32> _N_I_ESHT;
        partial void OnN_I_ESHTChanging(Nullable<global::System.Int32> value);
        partial void OnN_I_ESHTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> G_ST
        {
            get
            {
                return _G_ST;
            }
            set
            {
                OnG_STChanging(value);
                ReportPropertyChanging("G_ST");
                _G_ST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("G_ST");
                OnG_STChanged();
            }
        }
        private Nullable<global::System.Int32> _G_ST;
        partial void OnG_STChanging(Nullable<global::System.Int32> value);
        partial void OnG_STChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> G_S
        {
            get
            {
                return _G_S;
            }
            set
            {
                OnG_SChanging(value);
                ReportPropertyChanging("G_S");
                _G_S = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("G_S");
                OnG_SChanged();
            }
        }
        private Nullable<global::System.Int32> _G_S;
        partial void OnG_SChanging(Nullable<global::System.Int32> value);
        partial void OnG_SChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> M_1
        {
            get
            {
                return _M_1;
            }
            set
            {
                OnM_1Changing(value);
                ReportPropertyChanging("M_1");
                _M_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("M_1");
                OnM_1Changed();
            }
        }
        private Nullable<global::System.Int32> _M_1;
        partial void OnM_1Changing(Nullable<global::System.Int32> value);
        partial void OnM_1Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_socialsensorModel", Name="tbl_historical_objectives_data_game")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_historical_objectives_data_game : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_historical_objectives_data_game object.
        /// </summary>
        /// <param name="idHistorical">Initial value of the IdHistorical property.</param>
        /// <param name="w">Initial value of the W property.</param>
        public static tbl_historical_objectives_data_game Createtbl_historical_objectives_data_game(global::System.Int32 idHistorical, global::System.Int32 w)
        {
            tbl_historical_objectives_data_game tbl_historical_objectives_data_game = new tbl_historical_objectives_data_game();
            tbl_historical_objectives_data_game.IdHistorical = idHistorical;
            tbl_historical_objectives_data_game.W = w;
            return tbl_historical_objectives_data_game;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdHistorical
        {
            get
            {
                return _IdHistorical;
            }
            set
            {
                if (_IdHistorical != value)
                {
                    OnIdHistoricalChanging(value);
                    ReportPropertyChanging("IdHistorical");
                    _IdHistorical = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdHistorical");
                    OnIdHistoricalChanged();
                }
            }
        }
        private global::System.Int32 _IdHistorical;
        partial void OnIdHistoricalChanging(global::System.Int32 value);
        partial void OnIdHistoricalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdRow
        {
            get
            {
                return _IdRow;
            }
            set
            {
                OnIdRowChanging(value);
                ReportPropertyChanging("IdRow");
                _IdRow = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdRow");
                OnIdRowChanged();
            }
        }
        private global::System.String _IdRow;
        partial void OnIdRowChanging(global::System.String value);
        partial void OnIdRowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> G
        {
            get
            {
                return _G;
            }
            set
            {
                OnGChanging(value);
                ReportPropertyChanging("G");
                _G = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("G");
                OnGChanged();
            }
        }
        private Nullable<global::System.Int32> _G;
        partial void OnGChanging(Nullable<global::System.Int32> value);
        partial void OnGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 W
        {
            get
            {
                return _W;
            }
            set
            {
                OnWChanging(value);
                ReportPropertyChanging("W");
                _W = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("W");
                OnWChanged();
            }
        }
        private global::System.Int32 _W;
        partial void OnWChanging(global::System.Int32 value);
        partial void OnWChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> T
        {
            get
            {
                return _T;
            }
            set
            {
                OnTChanging(value);
                ReportPropertyChanging("T");
                _T = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("T");
                OnTChanged();
            }
        }
        private Nullable<global::System.Int32> _T;
        partial void OnTChanging(Nullable<global::System.Int32> value);
        partial void OnTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CN
        {
            get
            {
                return _CN;
            }
            set
            {
                OnCNChanging(value);
                ReportPropertyChanging("CN");
                _CN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CN");
                OnCNChanged();
            }
        }
        private Nullable<global::System.Int32> _CN;
        partial void OnCNChanging(Nullable<global::System.Int32> value);
        partial void OnCNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String U
        {
            get
            {
                return _U;
            }
            set
            {
                OnUChanging(value);
                ReportPropertyChanging("U");
                _U = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("U");
                OnUChanged();
            }
        }
        private global::System.String _U;
        partial void OnUChanging(global::System.String value);
        partial void OnUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DATE
        {
            get
            {
                return _DATE;
            }
            set
            {
                OnDATEChanging(value);
                ReportPropertyChanging("DATE");
                _DATE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DATE");
                OnDATEChanged();
            }
        }
        private global::System.String _DATE;
        partial void OnDATEChanging(global::System.String value);
        partial void OnDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TIME
        {
            get
            {
                return _TIME;
            }
            set
            {
                OnTIMEChanging(value);
                ReportPropertyChanging("TIME");
                _TIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TIME");
                OnTIMEChanged();
            }
        }
        private global::System.String _TIME;
        partial void OnTIMEChanging(global::System.String value);
        partial void OnTIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GAMEMODE
        {
            get
            {
                return _GAMEMODE;
            }
            set
            {
                OnGAMEMODEChanging(value);
                ReportPropertyChanging("GAMEMODE");
                _GAMEMODE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GAMEMODE");
                OnGAMEMODEChanged();
            }
        }
        private Nullable<global::System.Int32> _GAMEMODE;
        partial void OnGAMEMODEChanging(Nullable<global::System.Int32> value);
        partial void OnGAMEMODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HOST
        {
            get
            {
                return _HOST;
            }
            set
            {
                OnHOSTChanging(value);
                ReportPropertyChanging("HOST");
                _HOST = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HOST");
                OnHOSTChanged();
            }
        }
        private global::System.String _HOST;
        partial void OnHOSTChanging(global::System.String value);
        partial void OnHOSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> O_DE
        {
            get
            {
                return _O_DE;
            }
            set
            {
                OnO_DEChanging(value);
                ReportPropertyChanging("O_DE");
                _O_DE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O_DE");
                OnO_DEChanged();
            }
        }
        private Nullable<global::System.Int32> _O_DE;
        partial void OnO_DEChanging(Nullable<global::System.Int32> value);
        partial void OnO_DEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> O_SF
        {
            get
            {
                return _O_SF;
            }
            set
            {
                OnO_SFChanging(value);
                ReportPropertyChanging("O_SF");
                _O_SF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O_SF");
                OnO_SFChanged();
            }
        }
        private Nullable<global::System.Int32> _O_SF;
        partial void OnO_SFChanging(Nullable<global::System.Int32> value);
        partial void OnO_SFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> O_SCFA
        {
            get
            {
                return _O_SCFA;
            }
            set
            {
                OnO_SCFAChanging(value);
                ReportPropertyChanging("O_SCFA");
                _O_SCFA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O_SCFA");
                OnO_SCFAChanged();
            }
        }
        private Nullable<global::System.Int32> _O_SCFA;
        partial void OnO_SCFAChanging(Nullable<global::System.Int32> value);
        partial void OnO_SCFAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> N_O_DT
        {
            get
            {
                return _N_O_DT;
            }
            set
            {
                OnN_O_DTChanging(value);
                ReportPropertyChanging("N_O_DT");
                _N_O_DT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("N_O_DT");
                OnN_O_DTChanged();
            }
        }
        private Nullable<global::System.Int32> _N_O_DT;
        partial void OnN_O_DTChanging(Nullable<global::System.Int32> value);
        partial void OnN_O_DTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> G_ST
        {
            get
            {
                return _G_ST;
            }
            set
            {
                OnG_STChanging(value);
                ReportPropertyChanging("G_ST");
                _G_ST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("G_ST");
                OnG_STChanged();
            }
        }
        private Nullable<global::System.Int32> _G_ST;
        partial void OnG_STChanging(Nullable<global::System.Int32> value);
        partial void OnG_STChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> G_S
        {
            get
            {
                return _G_S;
            }
            set
            {
                OnG_SChanging(value);
                ReportPropertyChanging("G_S");
                _G_S = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("G_S");
                OnG_SChanged();
            }
        }
        private Nullable<global::System.Int32> _G_S;
        partial void OnG_SChanging(Nullable<global::System.Int32> value);
        partial void OnG_SChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> M_1
        {
            get
            {
                return _M_1;
            }
            set
            {
                OnM_1Changing(value);
                ReportPropertyChanging("M_1");
                _M_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("M_1");
                OnM_1Changed();
            }
        }
        private Nullable<global::System.Int32> _M_1;
        partial void OnM_1Changing(Nullable<global::System.Int32> value);
        partial void OnM_1Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_socialsensorModel", Name="tbl_interpretation_correlation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_interpretation_correlation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_interpretation_correlation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static tbl_interpretation_correlation Createtbl_interpretation_correlation(global::System.Int32 id)
        {
            tbl_interpretation_correlation tbl_interpretation_correlation = new tbl_interpretation_correlation();
            tbl_interpretation_correlation.Id = id;
            return tbl_interpretation_correlation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private Nullable<global::System.Double> _Val;
        partial void OnValChanging(Nullable<global::System.Double> value);
        partial void OnValChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ponderation
        {
            get
            {
                return _Ponderation;
            }
            set
            {
                OnPonderationChanging(value);
                ReportPropertyChanging("Ponderation");
                _Ponderation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ponderation");
                OnPonderationChanged();
            }
        }
        private Nullable<global::System.Int32> _Ponderation;
        partial void OnPonderationChanging(Nullable<global::System.Int32> value);
        partial void OnPonderationChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_socialsensorModel", Name="tbl_pearson_significance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_pearson_significance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_pearson_significance object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static tbl_pearson_significance Createtbl_pearson_significance(global::System.Int32 id)
        {
            tbl_pearson_significance tbl_pearson_significance = new tbl_pearson_significance();
            tbl_pearson_significance.Id = id;
            return tbl_pearson_significance;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> N
        {
            get
            {
                return _N;
            }
            set
            {
                OnNChanging(value);
                ReportPropertyChanging("N");
                _N = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("N");
                OnNChanged();
            }
        }
        private Nullable<global::System.Int32> _N;
        partial void OnNChanging(Nullable<global::System.Int32> value);
        partial void OnNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> atr1
        {
            get
            {
                return _atr1;
            }
            set
            {
                Onatr1Changing(value);
                ReportPropertyChanging("atr1");
                _atr1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("atr1");
                Onatr1Changed();
            }
        }
        private Nullable<global::System.Double> _atr1;
        partial void Onatr1Changing(Nullable<global::System.Double> value);
        partial void Onatr1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> atr2
        {
            get
            {
                return _atr2;
            }
            set
            {
                Onatr2Changing(value);
                ReportPropertyChanging("atr2");
                _atr2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("atr2");
                Onatr2Changed();
            }
        }
        private Nullable<global::System.Double> _atr2;
        partial void Onatr2Changing(Nullable<global::System.Double> value);
        partial void Onatr2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> atr3
        {
            get
            {
                return _atr3;
            }
            set
            {
                Onatr3Changing(value);
                ReportPropertyChanging("atr3");
                _atr3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("atr3");
                Onatr3Changed();
            }
        }
        private Nullable<global::System.Double> _atr3;
        partial void Onatr3Changing(Nullable<global::System.Double> value);
        partial void Onatr3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> atr4
        {
            get
            {
                return _atr4;
            }
            set
            {
                Onatr4Changing(value);
                ReportPropertyChanging("atr4");
                _atr4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("atr4");
                Onatr4Changed();
            }
        }
        private Nullable<global::System.Double> _atr4;
        partial void Onatr4Changing(Nullable<global::System.Double> value);
        partial void Onatr4Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_socialsensorModel", Name="tbl_spearmen_significance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_spearmen_significance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_spearmen_significance object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static tbl_spearmen_significance Createtbl_spearmen_significance(global::System.Int32 id)
        {
            tbl_spearmen_significance tbl_spearmen_significance = new tbl_spearmen_significance();
            tbl_spearmen_significance.Id = id;
            return tbl_spearmen_significance;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> N
        {
            get
            {
                return _N;
            }
            set
            {
                OnNChanging(value);
                ReportPropertyChanging("N");
                _N = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("N");
                OnNChanged();
            }
        }
        private Nullable<global::System.Int32> _N;
        partial void OnNChanging(Nullable<global::System.Int32> value);
        partial void OnNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> atr1
        {
            get
            {
                return _atr1;
            }
            set
            {
                Onatr1Changing(value);
                ReportPropertyChanging("atr1");
                _atr1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("atr1");
                Onatr1Changed();
            }
        }
        private Nullable<global::System.Double> _atr1;
        partial void Onatr1Changing(Nullable<global::System.Double> value);
        partial void Onatr1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> atr2
        {
            get
            {
                return _atr2;
            }
            set
            {
                Onatr2Changing(value);
                ReportPropertyChanging("atr2");
                _atr2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("atr2");
                Onatr2Changed();
            }
        }
        private Nullable<global::System.Double> _atr2;
        partial void Onatr2Changing(Nullable<global::System.Double> value);
        partial void Onatr2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> atr3
        {
            get
            {
                return _atr3;
            }
            set
            {
                Onatr3Changing(value);
                ReportPropertyChanging("atr3");
                _atr3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("atr3");
                Onatr3Changed();
            }
        }
        private Nullable<global::System.Double> _atr3;
        partial void Onatr3Changing(Nullable<global::System.Double> value);
        partial void Onatr3Changed();

        #endregion

    
    }

    #endregion

    
}
