package HolaApp;


/**
* HolaApp/HolaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* lunes 18 de agosto de 2014 09:53:23 AM CDT
*/

public interface HolaOperations 
{
  String saludar ();
  int sumar (int x, int y);
} // interface HolaOperations
