package HolaApp;

/**
* HolaApp/HolaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* lunes 18 de agosto de 2014 09:53:23 AM CDT
*/

public final class HolaHolder implements org.omg.CORBA.portable.Streamable
{
  public HolaApp.Hola value = null;

  public HolaHolder ()
  {
  }

  public HolaHolder (HolaApp.Hola initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HolaApp.HolaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HolaApp.HolaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HolaApp.HolaHelper.type ();
  }

}
