//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DBCasaModel", "FK_TblUsuarios_TblTiposUsuarios", "TblTiposUsuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ConsumirJSON.Model.TblTiposUsuarios), "TblUsuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConsumirJSON.Model.TblUsuarios), true)]

#endregion

namespace ConsumirJSON.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBCasaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBCasaEntities object using the connection string found in the 'DBCasaEntities' section of the application configuration file.
        /// </summary>
        public DBCasaEntities() : base("name=DBCasaEntities", "DBCasaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBCasaEntities object.
        /// </summary>
        public DBCasaEntities(string connectionString) : base(connectionString, "DBCasaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBCasaEntities object.
        /// </summary>
        public DBCasaEntities(EntityConnection connection) : base(connection, "DBCasaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblEstudiantes> TblEstudiantes
        {
            get
            {
                if ((_TblEstudiantes == null))
                {
                    _TblEstudiantes = base.CreateObjectSet<TblEstudiantes>("TblEstudiantes");
                }
                return _TblEstudiantes;
            }
        }
        private ObjectSet<TblEstudiantes> _TblEstudiantes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblTiposUsuarios> TblTiposUsuarios
        {
            get
            {
                if ((_TblTiposUsuarios == null))
                {
                    _TblTiposUsuarios = base.CreateObjectSet<TblTiposUsuarios>("TblTiposUsuarios");
                }
                return _TblTiposUsuarios;
            }
        }
        private ObjectSet<TblTiposUsuarios> _TblTiposUsuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblUsuarios> TblUsuarios
        {
            get
            {
                if ((_TblUsuarios == null))
                {
                    _TblUsuarios = base.CreateObjectSet<TblUsuarios>("TblUsuarios");
                }
                return _TblUsuarios;
            }
        }
        private ObjectSet<TblUsuarios> _TblUsuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblEstudiantes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblEstudiantes(TblEstudiantes tblEstudiantes)
        {
            base.AddObject("TblEstudiantes", tblEstudiantes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblTiposUsuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblTiposUsuarios(TblTiposUsuarios tblTiposUsuarios)
        {
            base.AddObject("TblTiposUsuarios", tblTiposUsuarios);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblUsuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblUsuarios(TblUsuarios tblUsuarios)
        {
            base.AddObject("TblUsuarios", tblUsuarios);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBCasaModel", Name="TblEstudiantes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblEstudiantes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblEstudiantes object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apPaterno">Initial value of the ApPaterno property.</param>
        /// <param name="apMaterno">Initial value of the ApMaterno property.</param>
        /// <param name="matricula">Initial value of the Matricula property.</param>
        public static TblEstudiantes CreateTblEstudiantes(global::System.Int32 id, global::System.String nombre, global::System.String apPaterno, global::System.String apMaterno, global::System.String matricula)
        {
            TblEstudiantes tblEstudiantes = new TblEstudiantes();
            tblEstudiantes.Id = id;
            tblEstudiantes.Nombre = nombre;
            tblEstudiantes.ApPaterno = apPaterno;
            tblEstudiantes.ApMaterno = apMaterno;
            tblEstudiantes.Matricula = matricula;
            return tblEstudiantes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApPaterno
        {
            get
            {
                return _ApPaterno;
            }
            set
            {
                OnApPaternoChanging(value);
                ReportPropertyChanging("ApPaterno");
                _ApPaterno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApPaterno");
                OnApPaternoChanged();
            }
        }
        private global::System.String _ApPaterno;
        partial void OnApPaternoChanging(global::System.String value);
        partial void OnApPaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApMaterno
        {
            get
            {
                return _ApMaterno;
            }
            set
            {
                OnApMaternoChanging(value);
                ReportPropertyChanging("ApMaterno");
                _ApMaterno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApMaterno");
                OnApMaternoChanged();
            }
        }
        private global::System.String _ApMaterno;
        partial void OnApMaternoChanging(global::System.String value);
        partial void OnApMaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Matricula
        {
            get
            {
                return _Matricula;
            }
            set
            {
                OnMatriculaChanging(value);
                ReportPropertyChanging("Matricula");
                _Matricula = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Matricula");
                OnMatriculaChanged();
            }
        }
        private global::System.String _Matricula;
        partial void OnMatriculaChanging(global::System.String value);
        partial void OnMatriculaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBCasaModel", Name="TblTiposUsuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblTiposUsuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblTiposUsuarios object.
        /// </summary>
        /// <param name="idTipoUsuario">Initial value of the IdTipoUsuario property.</param>
        /// <param name="tipoUsuario">Initial value of the TipoUsuario property.</param>
        public static TblTiposUsuarios CreateTblTiposUsuarios(global::System.Int32 idTipoUsuario, global::System.String tipoUsuario)
        {
            TblTiposUsuarios tblTiposUsuarios = new TblTiposUsuarios();
            tblTiposUsuarios.IdTipoUsuario = idTipoUsuario;
            tblTiposUsuarios.TipoUsuario = tipoUsuario;
            return tblTiposUsuarios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoUsuario
        {
            get
            {
                return _IdTipoUsuario;
            }
            set
            {
                if (_IdTipoUsuario != value)
                {
                    OnIdTipoUsuarioChanging(value);
                    ReportPropertyChanging("IdTipoUsuario");
                    _IdTipoUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdTipoUsuario");
                    OnIdTipoUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdTipoUsuario;
        partial void OnIdTipoUsuarioChanging(global::System.Int32 value);
        partial void OnIdTipoUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoUsuario
        {
            get
            {
                return _TipoUsuario;
            }
            set
            {
                OnTipoUsuarioChanging(value);
                ReportPropertyChanging("TipoUsuario");
                _TipoUsuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TipoUsuario");
                OnTipoUsuarioChanged();
            }
        }
        private global::System.String _TipoUsuario;
        partial void OnTipoUsuarioChanging(global::System.String value);
        partial void OnTipoUsuarioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBCasaModel", "FK_TblUsuarios_TblTiposUsuarios", "TblUsuarios")]
        public EntityCollection<TblUsuarios> TblUsuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblUsuarios>("DBCasaModel.FK_TblUsuarios_TblTiposUsuarios", "TblUsuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblUsuarios>("DBCasaModel.FK_TblUsuarios_TblTiposUsuarios", "TblUsuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBCasaModel", Name="TblUsuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblUsuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblUsuarios object.
        /// </summary>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellidoPaterno">Initial value of the ApellidoPaterno property.</param>
        public static TblUsuarios CreateTblUsuarios(global::System.Int32 idUsuario, global::System.String username, global::System.String password, global::System.String nombre, global::System.String apellidoPaterno)
        {
            TblUsuarios tblUsuarios = new TblUsuarios();
            tblUsuarios.IdUsuario = idUsuario;
            tblUsuarios.Username = username;
            tblUsuarios.Password = password;
            tblUsuarios.Nombre = nombre;
            tblUsuarios.ApellidoPaterno = apellidoPaterno;
            return tblUsuarios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApellidoPaterno
        {
            get
            {
                return _ApellidoPaterno;
            }
            set
            {
                OnApellidoPaternoChanging(value);
                ReportPropertyChanging("ApellidoPaterno");
                _ApellidoPaterno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApellidoPaterno");
                OnApellidoPaternoChanged();
            }
        }
        private global::System.String _ApellidoPaterno;
        partial void OnApellidoPaternoChanging(global::System.String value);
        partial void OnApellidoPaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApellidoMaterno
        {
            get
            {
                return _ApellidoMaterno;
            }
            set
            {
                OnApellidoMaternoChanging(value);
                ReportPropertyChanging("ApellidoMaterno");
                _ApellidoMaterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApellidoMaterno");
                OnApellidoMaternoChanged();
            }
        }
        private global::System.String _ApellidoMaterno;
        partial void OnApellidoMaternoChanging(global::System.String value);
        partial void OnApellidoMaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTipoUsuario
        {
            get
            {
                return _IdTipoUsuario;
            }
            set
            {
                OnIdTipoUsuarioChanging(value);
                ReportPropertyChanging("IdTipoUsuario");
                _IdTipoUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoUsuario");
                OnIdTipoUsuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTipoUsuario;
        partial void OnIdTipoUsuarioChanging(Nullable<global::System.Int32> value);
        partial void OnIdTipoUsuarioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBCasaModel", "FK_TblUsuarios_TblTiposUsuarios", "TblTiposUsuarios")]
        public TblTiposUsuarios TblTiposUsuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblTiposUsuarios>("DBCasaModel.FK_TblUsuarios_TblTiposUsuarios", "TblTiposUsuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblTiposUsuarios>("DBCasaModel.FK_TblUsuarios_TblTiposUsuarios", "TblTiposUsuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblTiposUsuarios> TblTiposUsuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblTiposUsuarios>("DBCasaModel.FK_TblUsuarios_TblTiposUsuarios", "TblTiposUsuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblTiposUsuarios>("DBCasaModel.FK_TblUsuarios_TblTiposUsuarios", "TblTiposUsuarios", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
