package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* jueves 12 de enero de 2017 09:07:20 PM CST
*/

public interface CalculadoraOperations 
{
  String saludar ();
  int sumar (int x, int y);
} // interface CalculadoraOperations
